# Generated by Django 5.0.6 on 2024-07-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=300)),
                ('productprice', models.IntegerField()),
                ('productdescription', models.TextField()),
            ],
        ),
    ]
