# Generated by Django 5.0.6 on 2024-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productimage',
            field=models.ImageField(default='none', upload_to='product_images'),
        ),
    ]
