# Generated by Django 5.0.6 on 2024-07-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addlist', '0002_products_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productimage',
            field=models.ImageField(default='none', upload_to='product_images/'),
        ),
    ]
